### ISSUE TITLE
new code in Scrollycode blocks won't render reliably

### ISSUE THREAD

**Issue by evanorti** [pomber/docusaurus-mdx-2#1]
If I change a scrollycode block to add code, the output will not show correctly. Often the codeblock output breaks or will not display the correct code. 

In the following example, I would like to use this feature to introduce each command as a new line of code added to the Scrollycode block output:

````md
<CH.Scrollycoding>

1. Make a new directory.

```sh focus=1:2
mkdir my-app
cd my-app
```

---

2. Set 'stable' as the default release channel.

```sh focus=4
mkdir my-app
cd my-app

rustup default stable
```

---

3. Add WASM as the compilation target.


```sh focus=6
mkdir my-app
cd my-app

rustup default stable

rustup target add wasm32-unknown-unknown

```

---

4. Install the following packages to generate the contract.


```sh focus=8:9
mkdir my-app
cd my-app

rustup default stable

rustup target add wasm32-unknown-unknown

cargo install cargo-generate --features vendored-openssl
cargo install cargo-run-script

```
</CH.Scrollycoding>
````

This occurs when testing locally with `npm run start` using Safari or Chrome browser.

**Comment by pomber** [comment]
I can't reproduce it or not sure if I understand the issue. Can you provide an example repo? and maybe a screenshot with the issue. Same for #2

**Comment by evanorti** [comment]
Found the problem. Following the docusaurus tutorial on the site gave me some different dependencies in package.json than the example. 

Updating dependencies to the same as 
https://github.com/code-hike/codehike/blob/main/examples/docusaurus/package.json 
fixed the issue.
