### ISSUE TITLE
Background color will not change with Shiki themes

### ISSUE THREAD

**Issue by evanorti** [pomber/docusaurus-mdx-2#2]
When I change Shiki syntax highlighting themes, the syntax highlighting colors will change, but the codeblock background remains the same dark color. I suppose this can be changed with CSS, but It would be nice to have the background change with the theme rather than adding custom CSS.

**Comment by evanorti** [comment]
It would also be great if Shiki themes background and default undefined syntax colors were applied to `inline code` colors.

**Comment by pomber** [comment]
> When I change Shiki syntax highlighting themes, the syntax highlighting colors will change, but the codeblock background remains the same dark color.

Are you restarting the server after changing the theme?

> It would also be great if Shiki themes background and default undefined syntax colors were applied to inline code colors

You can use this syntax ``_`const foo = bar`_`` and it should use the theme colors, it works specially well inside Scrollycoding and Section components.

**Comment by evanorti** [comment]
Ah, I wasn't aware of _`const foo = bar`_

Updated dependencies per my comment in #1 and everything works now.
