### ISSUE TITLE
Errors returned with Remark plugins 

### ISSUE THREAD

**Issue by evanorti** [pomber/docusaurus-mdx-2#5]
I want to use the katex and math remark plugins for parsing formulas, but I am getting errors:

```
Could not parse expression with acorn: Unexpected character '@'
```

It seems this happens to other remark plugins as well, such as the admonitions plugin (as specified in this repo's readme). I'd also like to use the directives plugin for simpler syntax, but am running into the same issue. 

Is there any workaround for this, so I can still use Code Hike and these plugins?

Thanks

**Comment by pomber** [comment]
I tried with `remark-math` and `rehype-katex` and I don't see any error: https://stackblitz.com/edit/github-hdma5n?file=docusaurus.config.js,docs%2Fintro.md&initialpath=docs/intro

Make sure the versions you are using work with mdx v2. If you are still having problems, post a stackblitz example and I'll take a look.

**Comment by pomber** [comment]
Also, make sure to escape any opening braces `{` that aren't part of expressions. See here: https://mdxjs.com/docs/troubleshooting-mdx/#could-not-parse-expression-with-acorn-error

**Comment by evanorti** [comment]
@pomber Interesting, on my setup your example is showing that equations still aren't being parsed into katex. 

I'll try some things and then post a stackblitz example.

![Screen Shot 2022-08-05 at 10 14 02 AM](https://user-images.githubusercontent.com/87997759/183127775-98e2a13f-e52a-4da1-bb21-b74f1e1e4248.png)

**Comment by evanorti** [comment]
Still can't get any of our other remark plugins are able to work either it seems.

Stackblitz here:

https://stackblitz.com/edit/tdocs?file=docusaurus.config.js

**Comment by evanorti** [comment]
Seems related to your comment here:

https://github.com/facebook/docusaurus/issues/4029#issuecomment-1098451055

**Comment by evanorti** [comment]
Using remark directives would also be helpful for us.

**Comment by pomber** [comment]
> Seems related to your comment here:
> 
> [facebook/docusaurus#4029 (comment)](https://github.com/facebook/docusaurus/issues/4029#issuecomment-1098451055)

Admonition doesn't work with mdx v2. Math and katex should work (according to the remark-math docs). 

But I'm not familiar with those plugins. I don't see any error, and I don't know what's the expected output. It would help if you could provide an example with the correct output (maybe using another framework that support mdx v2, like nextjs).

**Comment by evanorti** [comment]
I found an example of what Katex math equations should look like using next.js mdx2, rehypeKatex and remarkMath:

https://codesandbox.io/s/next-mdx-math-katex-vd1qx?file=/package.json

Let me know if you need anything else.

**Comment by pomber** [comment]
I updated the plugins in your example 
```
    "rehype-katex": "^6.0.2",
    "remark-math": "^5.1.1"
```


Looks like it works now https://stackblitz.com/edit/tdocs-vjasmd?file=docs%2Findex.mdx

![image](https://user-images.githubusercontent.com/1911623/183239907-d7c25c0a-a267-4e9b-b9ac-cb55ebddc424.png)

**Comment by evanorti** [comment]
Awesome! Thank you for your help!
